#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.7.0
// Descriptor size: 36 (bytes)
// +----------+--------+-------------------+
// | ReportId | Kind   | ReportSizeInBytes |
// +----------+--------+-------------------+
// |        1 | Input  |                 1 |
// +----------+--------+-------------------+
// |        1 | Output |                 1 |
// +----------+--------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x06, 0x22, 0xFF,    // UsagePage(LitButton[0xFF22])
    0x09, 0x01,          // UsageId(LitButton[0x0001])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x09, 0x02,          //     UsageId(Button[0x0002])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x25, 0x01,          //     LogicalMaximum(1)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x01,          //     ReportSize(1)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x07,          //     ReportSize(7)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x03,          //     UsageId(LED[0x0003])
    0x75, 0x01,          //     ReportSize(1)
    0x91, 0x02,          //     Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x75, 0x07,          //     ReportSize(7)
    0x91, 0x03,          //     Output(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[1];
};

#define HID_REPORT_OUTPUT1_ID (1)
struct HidReportOutput1
{
    uint8_t ReportId = HID_REPORT_OUTPUT1_ID;
    uint8_t Payload[1];
};

#pragma pack(pop)